/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AllIndexRouteImport } from './routes/all.index'
import { Route as AllMIdRouteImport } from './routes/all.$mId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllIndexRoute = AllIndexRouteImport.update({
  id: '/all/',
  path: '/all/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllMIdRoute = AllMIdRouteImport.update({
  id: '/all/$mId',
  path: '/all/$mId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all/$mId': typeof AllMIdRoute
  '/all': typeof AllIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all/$mId': typeof AllMIdRoute
  '/all': typeof AllIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/all/$mId': typeof AllMIdRoute
  '/all/': typeof AllIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/all/$mId' | '/all'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/all/$mId' | '/all'
  id: '__root__' | '/' | '/all/$mId' | '/all/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllMIdRoute: typeof AllMIdRoute
  AllIndexRoute: typeof AllIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all/': {
      id: '/all/'
      path: '/all'
      fullPath: '/all'
      preLoaderRoute: typeof AllIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all/$mId': {
      id: '/all/$mId'
      path: '/all/$mId'
      fullPath: '/all/$mId'
      preLoaderRoute: typeof AllMIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllMIdRoute: AllMIdRoute,
  AllIndexRoute: AllIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
